#include <iostream>
using namespace std;

int main() {
    int n;
    
    // Ask the user for input
    cout << "Enter a positive integer n: ";
    cin >> n;  // Input value for n
    
    cout << "The sequence generated by the Weird Algorithm for n = " << n << " is: " << endl;

    // Loop until n becomes 1
    while (n != 1) {
        cout << n << " ";  // Print the current value of n
        if (n % 2 == 0) {
            n /= 2;  // If n is even, divide it by 2
        } else {
            n = n * 3 + 1;  // If n is odd, multiply it by 3 and add 1
        }
    }
    cout << n << endl;  // Print the final value of n (which will be 1)
    
    return 0;
}